added files to repo
prime-slam/hidden-points-removal pull request #1
Opened 2023-07-24 22:38 UTC by AnNyiiik

2023-07-25 07:00 UTC, vnmsklnk requested changes
Let's rename `PointRemovalScripts` to `points_removal_scripts`. 
https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

2023-07-25 07:00 UTC, vnmsklnk commented on Dataset/cloud_paths
Why do we need this file?

2023-07-25 07:00 UTC, vnmsklnk commented on Dataset/mesh_paths
and this

2023-07-25 07:00 UTC, vnmsklnk commented on Dataset/pc_uv_labelled_01.xyz
Let's remove point clouds from repo

2023-07-25 07:00 UTC, vnmsklnk commented on Dockerfile
> +COPY . /workspace
```suggestion

COPY . /workspace
```

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_open3d.py
> +    str(path)
```python
path = str(path)
```
but it's better just like this:
```python
pcd = o3d.io.read_point_cloud(str(path))
```

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_open3d.py
> +    #o3d.visualization.draw_geometries([pcd])
Repository should not contain commented code

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_open3d.py
> +    #Define parameters used for hidden_point_removal
```suggestion
    # Define parameters used for hidden_point_removal
```

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_open3d.py
> +    #Get all points that are visible from given view point
```suggestion
    # Get all points that are visible from given view point
```
Let's fix it everywhere

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_open3d.py
> +def visualize(pcd):
I think we don't need this

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_ours.py
> +    mesh = o3d.io.read_triangle_mesh(mesh_path)
This is a tricky move, but I want the mesh to be created using `make_it_dense` when the function is called, and not read from a pre-created file

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/HPR_ours.py
> +    #o3d.visualization.draw_geometries([new_pcd])
same about commented code

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/__pycache__/HPR_open3d.cpython-39.pyc
This file is unnecessary

2023-07-25 07:00 UTC, vnmsklnk commented on PointsRemovalScripts/__pycache__/HPR_ours.cpython-39.pyc
and this

2023-07-25 07:00 UTC, vnmsklnk commented on experiments.py
> +sys.path.insert(1, '/workspace/PointsRemovalScripts')
You don't really need this

2023-07-25 07:00 UTC, vnmsklnk commented on experiments.py
> +        return "empty cloud"
You should raise exception in this case

2023-07-25 07:00 UTC, vnmsklnk commented on experiments.py
> +command_line_args = sys.argv[1:]
Something strange here. Let this script take path to the cloud as input and calculate the accuracy of both Open3D method and our method at the same time

2023-07-26 07:33 UTC, vnmsklnk requested changes
Let's use black formatter to make the code look better

2023-07-26 07:33 UTC, vnmsklnk commented on experiments.py
> +cloud_path = sys.argv[1]
Let's use `argparse` for this
Example https://github.com/vnmsklnk/ORB-SLAM3-Datasets-Preprocessing/blob/ef52b055df08453b20a46b6812e6570505e3d207/scripts/associate_one_view.py#L43

2023-07-26 07:33 UTC, vnmsklnk commented on experiments.py
> +    index = 0
why do you need this? you can always get cloud size like this `len(marked_visibility)`

2023-07-26 07:33 UTC, vnmsklnk commented on experiments.py
> +        estimated_visibility[i] = 1
```suggestion
estimated_visibility = np.zeros(cloud_size)
visible_indexes = np.asarray(pt_map)
estimated_visibility[visible_indexes] = 1
```

2023-07-26 07:33 UTC, vnmsklnk commented on points_removal_scripts/mesh_based_script/HPR_mesh_based.py
> +import subprocess
Do you really need `subprocess` now?

2023-07-26 07:33 UTC, vnmsklnk commented on points_removal_scripts/mesh_based_script/mesh_generation.py
> +#!/usr/bin/env python3
it is usefull for console scripts, unnecessary now

2023-07-26 07:33 UTC, vnmsklnk commented on experiments.py
> +import numpy as np
Let's sort imports alphabetically and by type.
At first `import ...` and then `from ...`. They must be divided by empty line.
Here it can look like this:
```suggestion
import numpy as np
import sys

from points_removal_scripts.mesh_based_script import HPR_mesh_based
from points_removal_scripts.open3d_based_script import HPR_open3d
```

2023-07-26 07:33 UTC, vnmsklnk commented on Dockerfile
> +    sed -i 's/python/python3/g' test_scan.py
It is unnecessary now because we don't use `test_scan.py` anymore

2023-07-26 21:41 UTC, AnNyiiik commented on Dataset/cloud_paths
<img width="1352" alt="HPR_open3d_before" src="https://github.com/prime-slam/hidden-points-removal/assets/114094098/3564410e-98f3-484f-8f26-49808f213148">
<img width="1352" alt="HPR_open3d_before" src="https://github.com/prime-slam/hidden-points-removal/assets/114094098/7111af30-3fae-46a0-83ae-a2952c3fdb8e">

2023-07-27 18:06 UTC, vnmsklnk approved these changes

2023-07-27 19:21 UTC, merged